api/views.py
from hashlib import md5
from io import BytesIO
import ssl
from flask import Blueprint, jsonify, render_template, redirect, request, flash, send_file, url_for, Response, session, abort
from flask_login import current_user, login_required
from api.models import Post, User, db, ImagePost, Comments
from pymongo import MongoClient
from bson.objectid import ObjectId
from gridfs import GridFS
import certifi


ca = certifi.where()

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    page = request.args.get('page', default=1, type=int)
    posts_per_page = 5
    offset = (page - 1) * posts_per_page
    posts = Post.objects().skip(offset).limit(posts_per_page).order_by('-timestamp')
    post_len = len(Post.objects())
    return render_template('index.html', user=current_user, post=posts, page=page, post_len=post_len, posts_per_page=posts_per_page)

@views.route('/news', methods=['GET', 'POST'])
@login_required
def news():
    page = request.args.get('page', default=1, type=int)
    posts_per_page = 2
    offset = (page - 1) * posts_per_page
    posts = Post.objects().skip(offset).limit(posts_per_page).order_by('-timestamp')
    post_len = len(Post.objects())
    return render_template('news.html', user=current_user, post=posts, page=page, post_len=post_len, posts_per_page=posts_per_page)

@views.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    if request.method == 'POST':
        textpost = request.form.get('textpost')
        imagepost = request.form.get('imagepost')
        linkpost = request.form.get('linkpost')
        print(request.form)

        if textpost == 'on' and imagepost != 'on' and linkpost != 'on':
            return redirect(url_for('views.textpost'))
        elif imagepost == 'on' and linkpost != 'on' and textpost != 'on':
            return redirect(url_for('views.imagepost'))
        elif linkpost == 'on' and textpost != 'on' and imagepost != 'on':
            return redirect(url_for('views.linkpost'))
        else:
            flash('Must Select One Post Type', category='error')
    return render_template('post.html', user=current_user)


@views.route('/image/<image_id>')
def get_image(image_id):
    #print(db)  replace with your database name
    fs = GridFS(db)
    file_id = ObjectId(image_id)
    file = fs.get(file_id)
    response = Response(file.read(), mimetype='image/*')
    return response

@views.route('/images/<id>')
def serve_image(id):
    img = ImagePost.objects.with_id(id)
    return send_file(BytesIO(img.image_path.read()), mimetype='image/jpeg')

@views.route('/profile/<username>', methods=['GET', 'POST'])
def profile(username):
    user = User.objects(username=username).first()
    if user:
        if request.method == "POST":
            new_username = request.form.get("change_username")
            new_profile_pic = request.files['change_profile_pic']
            if new_profile_pic:
                user = User.objects(username=username).first()
                if user.changed_profile_pic.read():
                    user.changed_profile_pic.delete()
                user.changed_profile_pic.put(new_profile_pic)
                user.save()
                flash('Profile picture changed', category='success')
                return redirect(f'/profile/{username}')
            if new_username:
                exist_user = User.objects(username=new_username).first()
                if exist_user:
                    flash('Username already taken, Try another', category='error')
                else:
                    User.objects(username=username).update(username=new_username)
                    flash('Username successfully changed', category='success')
                    return redirect(f'/profile/{new_username}')

        user = User.objects(username=username).first()
        page = request.args.get('page', default=1, type=int)
        posts_per_page = 5
        offset = (page - 1) * posts_per_page
        post = Post.objects(author=user).skip(offset).limit(posts_per_page).order_by('-timestamp')
        post_len = len(Post.objects(author=user))
        return render_template('profile.html', user=current_user, post=post, page=page, post_len=post_len, searched_user=user)
    
    else:
        abort(404)

@views.route('/makepost', methods=['POST'])
def makepost():
    user = User.objects(id=current_user.id).first()
    title = request.form.get('title')
    link = request.form.get('linkpost')
    image = request.files.get('imagepost')
    tag = request.form.get('tags')
    post = Post(author=user)
    if len(title) == "":
        flash('title must not be empty, say something', category='error')
    post.title = title
    post.link_url = link
    post.tags = tag
    if image.filename != "":
        post.image_path.put(image)
    post.save()
    flash('Post Created!', category='success')
    return redirect(url_for('views.home'))


@views.route('/profile/<username>/Edit_Profile', methods=['GET', 'POST'])
def edit_profile(username):
    if request.method == "POST":
        user = current_user
        print(request.form)
        new_username = request.form.get('change_username')
        new_email = request.form.get('change_email')
        new_profile_pic = request.files.get('change_profile_pic')
        bio = request.form.get('bio')

        user_email = User.objects(email=new_email).first()
        user_username = User.objects(username=new_username).first()

        if user_email and new_email != user.email:
            flash('A user with that email already exists, try again', category='error')
        elif user_username and new_username != user.username:
            flash('A user with that username already exists, try again', category='error')
        else:
            if new_email != user.email:
                user.update(email=new_email)
                flash('Email updated successfully')
            if new_username != user.username:
                user.update(username=new_username)
                flash('Username updated successfully')
            if bio is not None:
                print(bio)
                user.update(bio=bio)
                flash('Bio updated successfully')
        return redirect(url_for("views.edit_profile", username=user.username))

    return render_template('editprofile.html', user=current_user)

@views.route('/like/<post_id>', methods=['POST', 'GET'])
def like_post(post_id):
    post = Post.objects(id=post_id).first()
    current_user_like = None
    for liker in post.likes:
        if liker == current_user:
            current_user_like = liker
            break
    
    if current_user_like:
        post.likes.remove(current_user_like)
        has_liked = "unliked"
    else:
        post.likes.append(current_user)
        has_liked = "liked"
    post.save()
    return jsonify({'has_liked': has_liked})

@views.route('/comment/<post_id>', methods=['POST', 'GET'])
def comment_post(post_id):
    post = Post.objects(id=post_id).first()
    if request.method == "POST":
        content = request.form.get("comments")
        comment = Comments()
        comment.commenter = current_user
        comment.content = content
        post.comments.append(comment)
        post.save()
        flash('Successfully dropped your comment', category='success')
        return redirect(url_for('views.comment_post', post_id=post_id))
    len_likes = len(post.likes)
    return render_template('selectedpost.html', pos=post, user=current_user, likes=len_likes)

@views.route("/edit_post/<post_id>", methods=['POST'])
def edit_post(post_id):
    post = Post.objects(id=post_id).first()
    newText = request.form.get("edit_post_text")
    if newText == "":
        flash('Please input a valid text', category='error')
    print(newText)
    return redirect(f'/profile/{current_user.username}')

@views.route("/change_profile_picture/<username>", methods=['POST'])
def change_profile_picture(username):
    if request.method == "POST":
        user = User.objects(username=username).first()
        new_profile_pic = request.files.get('changed_profile_pic')
        print(new_profile_pic, user.changed_profile_pic, request.files)
        if new_profile_pic:
            if user.changed_profile_pic.read():
                user.changed_profile_pic.delete()
            user.changed_profile_pic.put(new_profile_pic)
            user.save()
            flash('Profile picture changed', category='success')
            return redirect(f'/profile/{username}')
    return render_template('editprofile.html', user=current_user)

api/templates/edit.html
{% extends "base.html" %}

{% block title %} E-ThrillHub | Edit {{ user.username }} {% endblock %}



{% block content %}
    {% if user.changed_profile_pic %}
        <div id="profile-div">
            <img src="/image/{{ user.changed_profile_pic._id }}" alt="" id="pro_pic" class="pp"> {{ user.username }}
        </div>
    {% else %}
        <div id="profile-div">
            <img src="{{ user.profile_pic }}" alt="" id="pro_pic" class="pp"> {{ user.username }}
        </div>
    {% endif %}

    <h2 style="text-align: center;">Edit Profile</h2>

    <div class="pro_pic_modal">
        <span class="close profile-pic-close">&times;</span>
    </div>

    <form action="" method="POST" enctype="multipart/form-data">
        <label for="change_username">Edit username</label>
        <input type="text" name="change_username" id="change_username" value="{{ user.username }}">
        <label for="change_email">Edit Email</label>
        <input type="email" name="change_email" id="change_email" value="{{ user.email }}">
        <label for="change_profile_pic">Edit Profile Picture</label>
        <input type="file" name="change_profile_pic" id="change_profile_pic">
        <button value="Delete Account" id="delete_acct">Delete Account</button>
        <button type="submit">SUBMIT</button>
    </form>
    <div class="del_acct_modal">
        <div class="del_acct_modal_content">
            <h3>Are you sure?</h3>
            <a href="/auth/delete_account">Yes</a>
            <span class="del_acct_cancel">No</span>
        </div>
    </div>
    <script>
        const getDelAcct = document.querySelector("#delete_acct");
        let getdelModal = document.querySelector(".del_acct_modal");
        getDelAcct.addEventListener("click", (event) => {
            event.preventDefault();
            getdelModal.style.display = "block";
        })

        let getDelAcctCancel = document.querySelector(".del_acct_cancel");
        getDelAcctCancel.addEventListener("click", (event) => {
            event.preventDefault();
            getdelModal.style.display = "none";
        })
    </script>
{% endblock %}

api/templates/editprofile.html
{% extends "base.html" %}
{% block title %} E-ThrillHub | Edit {{ user.username }} {% endblock %}

{% block content %}
    {% if user.changed_profile_pic %}
        <div id="profile-div" class="profile">
            <img src="/image/{{ user.changed_profile_pic._id }}" alt="{{ user.username }} Profile Picture" id="profile-picture" class="pp">
            <p>{{ user.username }}</p>
            <label for="changed_profile_pic">
            </label>
            <input type="file" id="upload-button" />
        </div>
    {% else %}
        <div id="profile-div" class="profile">
            <img src="{{ user.profile_pic }}" alt="{{ user.username }} Profile Picture" id="profile-picture" class="pp">
            <p> {{ user.username }} </p>
            <input type="file" id="upload-button" />
        </div>
    {% endif %}

    
    <div>
      <h2 style="text-align: center;" >Edit Profile</h2>

      <div class="pro_pic_modal">
        <span class="close profile-pic-close">x</span>

      </div>
    
      <form action="/profile/{{ user.username }}/Edit_Profile" method="POST" enctype="multipart/form-data" style="margin-top: 1rem;" class="form_edit_profile">
        <label for="change_username">Edit username</label>
        <input
          type="text"
          name="change_username"
          id="change_username"
          value="{{ user.username }}"
        />
        <label for="change_email">Edit Email</label>
        <input
          type="email"
          name="change_email"
          id="change_email"
          value="{{ user.email }}"
        />
        
        <label for="bio">Edit Bio</label>
        <textarea
          type="text"
          name="bio"
          id="bio"
        >
            {% if user.bio %} {{ user.bio }} {% endif %} 
        </textarea>
        
        <button type="submit" style="margin-top: 7px;">Submit</button>
        <button type="button" id="delete_acct" style="margin-top: 7px;">Delete Account</button>
    </form>

    
      <div class="del_acct_modal">
        <div class="del_acct_modal_content">
            <h3>Are you sure?</h3>
            <a href="/auth/delete_account">Yes</a>
            <span class="del_acct_cancel" style="cursor: pointer;">No</span>
        </div>
    </div>
    </div>

    <script>
        const getDelAcct = document.querySelector("#delete_acct");
        let getdelModal = document.querySelector(".del_acct_modal");
        let getdelCancel = document.querySelector(".del_acct_cancel");
        getDelAcct.addEventListener("click", (event) => {
          event.preventDefault();
          getdelModal.style.display = "block";
        });
  
        getdelCancel.addEventListener("click", () => {
          getdelModal.style.display = "none";
        })
  
        const getProfilePic = document.querySelector("#profile-picture");
        let getProfilePicModal = document.querySelector(".pro_pic_modal");
        let getProfilePicClose = document.querySelector(".profile-pic-close");
  
        getProfilePic.addEventListener("click", (event) => {
            if (event.target == getProfilePicModal) {
                getProfilePicModal.style.display = "none";
            }

            if (!document.querySelector("#changed_profile_pic")) {
                let newImg = document.createElement("img");
                newImg.src = getProfilePic.src;
                newImg.style.width = "50%";
                newImg.style.height = "50%";
                newImg.style.margin = "auto";
                newImg.style.display = "block";
                newImg.style.borderRadius = "50%";
                newImg.style.border = "2px solid #000";
                newImg.style.boxShadow = "0 0 10px #000";
                let newform = document.createElement("form");
                newform.action = "/change_profile_picture/{{ user.username }}";
                newform.method = "POST";
                newform.enctype = "multipart/form-data";
                let newinput = document.createElement("input");
                newinput.type = "file";
                newinput.name = "changed_profile_pic";
                newinput.id = "changed_profile_pic";
                newinput.style.display = "block";
                newinput.style.margin = "auto";
                newinput.style.marginTop = "1rem";
                let newbutton = document.createElement("button");
                newbutton.type = "submit";
                newbutton.style.display = "block";
                newbutton.style.margin = "auto";
                newbutton.style.marginTop = "1rem";
                newbutton.textContent = "Submit";
                getProfilePicModal.appendChild(newImg);
                newform.appendChild(newinput);
                newform.appendChild(newbutton);
                getProfilePicModal.appendChild(newform);
            }
            getProfilePicModal.style.display = "block";

        });

        getProfilePicClose.addEventListener("click", () => {
            getProfilePicModal.style.display = "none";
        });
      </script>
{% endblock %}

api/templates/imagepost.html
{% extends "base.html" %}

{% block title %} JustIn | Make a Post {% endblock %}

{% block content %}

    <form action="" method="POST" enctype="multipart/form-data">
        <label for="title">Title</label>
        <input type="text" name="title" id="title">
        <input type="file" name="imagepost" id="imagepost">
        <button type="submit">Post</button>
    </form>

{% endblock %}

api/templates/linkpost.html
{% extends "base.html" %}

{% block title %} JustIn | Make a Post {% endblock %}

{% block content %}

    <form action="" method="POST">
        <input type="url" name="link_url" id="linkpost">
        <button type="submit">Post</button>
    </form>

{% endblock %}

api/templates/log.html
{% extends "base.html" %}

{% block title %} E-ThrillHub | Login {% endblock %}

{% block auth %}
    <a href="/auth/signup" class="btn btn-primary" style="margin-bottom:1rem;">Sign up</a>
{% endblock %}
{% block content %}
    <div class="container py-5 px-5 bg" style="margin-top: 8rem;">
        <div class="row justify-content-between bg-white rounded-start-4">
            <div class="col-lg-7 d-flex justify-content-center align-items-center">
                <div class="login-card py-lg-0 py-5">
                    <h2 class="fw-semibold">Welcome to <br>E-THRILLHUB</h2>
                    <p class="fw-light">Welcome back ! Please login your Account</p>
                    <form action="" class="form" method="POST">
                        <div class="row">
                            <div class="mb-3 col-12">
                                <label for="email" class="mb-1 fw-medium">Email</label>
                                <input type="email" class="form-control" placeholder="Enter Email" name="email">
                            </div>
                            <div class="col-12">
                                <label for="password" class="mb-1 fw-medium">Password</label>
                                <input type="password" class="form-control" placeholder="Enter Password" name="password">
                            </div>
                            <div class="col-12 d-flex justify-content-between mt-3 checkbox">
                                <div class="d-flex">
                                    <input class="form-check-input" type="checkbox" name="remember_me">
                                    <label for="remember_me" class="fw-medium ms-2" style="font-size: 10px; text-shadow: 0 0 1px black;">
                                        Remember password
                                    </label>
                                </div>
                                <a href="#" class="fw-semibold text-decoration-none">Forgot password</a>
                            </div>
                        </div>
                        <button type="submit" class="btn mt-4 w-100">login</button>
                        <!---<button type="submit" class="btn mt-4 w-100 d-flex justify-content-center align-items-center">
                            <i class="bi bi-apple me-2 fs-5"></i>
                            <span>Log in with Apple</span>
                        </button>
                        <button type="submit" class="btn mt-4 w-100 d-flex justify-content-center align-items-center">
                            <img src="google.png" alt="" width="5%" class="me-2">
                            <img src="https://th.bing.com/th/id/R.677d0a76c3ac4d273a0e5eaf4390b9b9?rik=Q6NZvyd3Q5l68A&riu=http%3a%2f%2flofrev.net%2fwp-content%2fphotos%2f2016%2f06%2fgoogles_new_logo.png&ehk=U8tqNPcgWTxUbSquth5DmjOci1GN8mci21H7FfSPTm0%3d&risl=&pid=ImgRaw&r=0" alt="Google Logo" height="25">
                            <span>Log in with Google</span>
                        </button>-->
                    </form>
                    <p class="text-center signup mt-4">Don't have an account? <a href="/auth/signup"
                            class="text-decoration-none fw-semibold">Sign up now</a></p>
                </div>
            </div>
            <div class="col-lg-5 col-12 p-0">
                <img src="{{ url_for('static', filename='images/smiley-man-using-his-smartphone-while-home.jpg') }}"
                    alt="" class=" w-100">
            </div>
        </div>
    </div>
{% endblock %}

api/templates/news.html
{% extends "base.html" %}

{% block title %} E-ThrillHub | News {% endblock %}

{% block content %}
    {% for pos in post %}
        <div id="post_container">
            {% if pos.author.changed_profile_pic %}
            <a href="/profile/{{ pos.author.username }}" title="{{ pos.author.username }}">
                <div id="profile-div">
                    <img src="/image/{{ pos.author.changed_profile_pic._id }}" alt="" id="pro_pic" class="pp">
                </div>
            </a>
            {% else %}
                <a href="/profile/{{ pos.author.username }}" title="{{ pos.author.username }}">
                    <div id="profile-div">
                        <img src="{{ pos.author.profile_pic }}" alt="" id="pro_pic" class="pp">
                    </div>
                </a>
            {% endif %}
            <div id="post_header">
                <a id="post_username" href="/profile/{{ pos.author.username }}"> {{ pos.author.username }} </a>
                <p class="timestamp" data-timestamp="{{ pos.timestamp.isoformat() }}">Loading...</p>
                <p class="title"> {{ pos.title }} </p>
                {% if pos.link_url %}
                    <a href="{{ pos.link_url }}">{{ pos.link_url }}</a>
                {% endif %}
            </div>
            <div id="post_img">
                {% if pos.image_path %}
                    <img src="/image/{{ pos.image_path._id }}" alt="" class="post-image">
                {% endif %}
            </div>

            <ul>
                <li>
                    <button class="like_post {% if user in pos.likes %}liked{% else %}unliked{% endif %}" id="{{ pos.id }}">
                        <i class="fa fa-heart"></i>
                    </button>
                </li>
                <li>
                    <a href="/comment/{{ pos.id }}">
                        <i class="fa fa-comment"></i>
                    </a>
                </li>
            </ul>
        </div>
    {% endfor %}
    {% if page * posts_per_page < post_len %}
        <a href="{{ url_for('views.news', page=page + 1) }}">Next</a>
    {% endif %}
    {% if page > 1 %}
        <a href="{{ url_for('views.news', page=page - 1) }}">Previous</a>
    {% endif %}

{% endblock %}

api/templates/post.html
{% extends "base.html" %}

{% block title %} E-ThrillHub | Make a Post {% endblock %}

{% block content %}
  <form action="/makepost" method="POST" enctype="multipart/form-data" style="margin-top: 14rem;">
    <textarea name="title" id="post-content" cols="30" rows="10" placeholder="What's popping?" required="true"></textarea>
    <label for="imagepost" id="label-image">
        <i class="fa fa-picture-o" aria-hidden="true"></i>
    </label>
    <input type="file" name="imagepost" id="imagepost">
    <label for="tags" id="label-tags">
        <i class="fa fa-tag" aria-hidden="true"></i>
    </label>
    <input type="text" name="tags" id="tags">
    <div id="show-img">
        <span class="close img-close">×</span>
    </div>
    <button type="submit">Post</button>
</form>
  {% endblock %}

api/templates/selectedpost.html
{% extends "base.html" %}

{% block title %} E-ThrilHub ... {{ pos.author.username }}'s post {% endblock %}

{% block content %}
  <main>
    <article>


          <div class="hero-banner">

           
            <img src="{{ url_for('static', filename='images/pattern-2.svg') }}" width="27" height="26" alt="shape" class="shape shape-1">

            <img src="{{ url_for('static', filename='images/pattern-3.svg') }}" width="27" height="26" alt="shape" class="shape shape-2">

          </div>

          <img src="{{ url_for('static', filename='images/shadow-1.svg') }}" width="500" height="800" alt="" class="hero-bg hero-bg-1">

          <img src="{{ url_for('static', filename='images/shadow-2.svg') }}" width="500" height="500" alt="" class="hero-bg hero-bg-2">

        </div>
      </section>







      <!-- 
        - # POST
      -->

      <section class="section feature" aria-label="feature">
        <div class="container">

            <h2 class="headline headline-2 section-title">
              <span class="span">What People Say</span>
            </h2>
  
            <p class="section-text">
              You can add your comment about this post
            </p>
  
            <ul class="feature-list">
  
              <li>
                <div class="card feature-card" style="margin: 1rem; color: #ccc8c8;">
          
                  {% if pos.image_path %}
                    <figure class="card-banner img-holder" style="--width: 1602; --height: 903;">
                        <img src="/image/{{ pos.image_path._id }}"width="1602" height="903" loading="lazy"
                          alt="{{ pos.author.username }} - {{ pos.title }}" class="img-cover">
                    </figure>
                  {% endif %}
          
                                  <div class="card-content">
                                      <div class="card-wrapper">
                                      <div class="card-tag">
                                          <a href="#" class="span hover-2" >#Movies</a>
                                          <a href="#" class="span hover-2">#Action</a>
                                      </div>
                                      </div>
                                      
                                      <h3 class="headline headline-3">
                                      <p href="#" class="card-title hover-2">{{ pos.title }}</p>
                                      </h3>
                      
                                      <div class="card-wrapper">
                                      <div class="profile-card">
                                              {% if pos.author.changed_profile_pic %}
                                              <img src="/image/{{ pos.author.changed_profile_pic._id }}" width="48" height="48" loading="lazy" alt="pos.author.username in E-Thrillhub"
                                              class="profile-banner">
                                          {% else %}
                                              <img src="{{ pos.author.profile_pic }}" width="48" height="48" loading="lazy" alt="pos.author.username in E-Thrillhub"
                                              class="profile-banner">
                                          {% endif %}
                                          <div>
                                          <a href="/profile/{{ pos.author.username }}" class="card-title">{{ pos.author.username }}</a>
                                          <p class="card-subtitle timestamp card-subtitle" data-timestamp="{{ pos.timestamp.isoformat() }}"></p>
                                          </div>
                                      </div>
                                      {% if user in pos.likes %}
                                          <img src="{{ url_for('static', filename='images/icons8-love-48.png') }}" width="30" height="48" loading="lazy" alt="Joseph" class="love" id="{{ pos.id }}">
                                      {% else %}
                                          <img src="{{ url_for('static', filename='images/icons8-heart-50.png') }}" width="30" height="48" loading="lazy" alt="Joseph" class="love" id="{{ pos.id }}">
                                      {% endif %}
                                      <a href="/comment/{{ pos.id }}">
                                          <img src="{{ url_for('static', filename='images/comment.png' ) }}"  width="30" height="48" loading="lazy" alt="Joseph" class="comment">
                                      </a>
                                      <img src="{{ url_for('static', filename='images/icons8-share-48.png' ) }}" width="30" height="48" loading="lazy" alt="Joseph" class="share">
                                  </div>
                     
            </div>
                  </div>
                  

      
                  <!-- Comment Section -->
                  <div>
                    
                    <!-- Form to add new comments -->
                    <form class="comment-form" action="/comment/{{ pos.id }}" method="POST">
                      <textarea name="comments" id="comment" placeholder="Write your comment here..." rows="4" required="true"></textarea>
                      <button type="submit" class="btn btn-primary" style="margin-bottom:1rem; width:fit-content;">Comment</button>
                      </form>
                    <!-- List of comments -->
                  </div>
                  <!-- End of Comment Section -->
      
                </div>
              </li>
            </ul>
      
      

        
    </section>

    <section class="section feature" aria-label="feature">
        <div class="container">
  
            <h2 class="headline headline-2 section-title">
                <span class="span" style="display: flex;">Comments</span>
                <ul class="comments" id="comments-list">
                  {% with comments = pos.comments %}
                    {% if comments %}
                      {% for comment in comments %}
                        {% if comment.content %}
                        <div class="comment-contents" style="margin: 1rem;">
                          <a href="/profile/{{ comment.commenter.username }}" style="font-size: 25px;"> {{ comment.commenter.username }}
                            <span class="card-subtitle timestamp card-subtitle" data-timestamp="{{ comment.timestamp.isoformat() }}" style="font-size: 0.5em;">
                              
                            </span>
                          </a>
                          <li style="color: white; margin-left: 2rem ;">
                            {{ comment.content }}
                          </li>
                        </div>
                        {% endif %}
                      {% endfor %}
                    {% else %}
                        <h3 style="margin: 1rem;">
                          No comments yet, be the first to comment 😁
                        </h3>
                    {% endif %}
                  {% endwith %}
                </ul>
            </h2>
        </div>
    </section>
        
  
        
              
               

    


  





  <!-- 
    - #BACK TO TOP
  -->

  <a href="#top" class="back-top-btn" aria-label="back to top" data-back-top-btn>
    <ion-icon name="arrow-up-outline" aria-hidden="true"></ion-icon>
  </a>

  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

{% endblock %}

api/templates/signup.html
{% extends "base.html" %}

{% block title %}JustIn | Sign Up{% endblock %}


{% block content %}

<form action="" method="POST">
    <label for="username">Username</label>
    <input type="username" name="username" id="username" placeholder="Username">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" placeholder="Enter your Email">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" placeholder="Password">
    <label for="confirm_password">Confirm Password</label>
    <input type="password" name="confirm_password" id="confirm_password" placeholder="Confirm Password">
    <span>Already have an account? <a href="/auth/login">Login</a></span>
    <button type="submit" id="submit" >Sign Up</button>
</form>

{% endblock %}